version: '3'
services:
  web:
    image: drupaldocker/php:7.2-apache
    volumes:
      - ./docroot:/var/www/html:cached
    env_file:
      - ./docker.env
    ports:
      - "80:80"
  db:
    image: mysql:5.5
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    env_file:
      - ./docker.env
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./docker.env
    ports:
      - "8001:80"